name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Установка lcov
        run: sudo apt-get install lcov
      - uses: remarkablemark/setup-codeclimate@v2
      - uses: hrishikesh-kadam/setup-lcov@v1
      - name: Запуск тестов и сбор покрытия
        run: |
          rm -rf coverage/* coverage.info coverage.lcov
          cc-test-reporter before-build
          npm install
          npm i @vitest/coverage-v8
          npm run test-coverage
          lcov --rc branch_coverage=1 --capture --directory coverage --output-file coverage.info || echo "Не удалось создать coverage.info"
          lcov --remove coverage.info '*/tests/*' --output-file coverage.lcov || echo "Не удалось создать coverage.lcov"
          cc-test-reporter after-build -t lcov coverage.lcov --exit-code $? || echo "coverage.info не найден или пуст. Пропуск обработки." exit 0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
