name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Установка lcov
        run: sudo apt-get install lcov
      - uses: remarkablemark/setup-codeclimate@v2
      - uses: hrishikesh-kadam/setup-lcov@v1
      - name: Запуск тестов и сбор покрытия
        run: cc-test-reporter before-build

          lcov --directory coverage --zerocounters

          lcov --directory coverage --capture --output-file coverage.info

          lcov --remove coverage.info '*/tests/*' --output-file coverage.info

          cc-test-reporter after-build -t lcov coverage.info --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
